apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-safety-frontend
  labels:
    app: smart-safety-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-safety-frontend
  template:
    metadata:
      labels:
        app: smart-safety-frontend
    spec:
      containers:
      - name: smart-safety-frontend
        # 방금 푸시한 ECR 프론트엔드 이미지 주소.
        image: 549328952175.dkr.ecr.ap-northeast-2.amazonaws.com/smart-safety-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
        # 프론트엔드 빌드 시 필요한 환경 변수가 있다면 여기에 기재
        env:
        - name: VITE_BACKEND_BASE_URL
          value: "http://smart-safety-backend-service:8080" # 백엔드 서비스 이름을 도메인처럼 사용.

---
apiVersion: v1
kind: Service
metadata:
  name: smart-safety-frontend-service
spec:
  type: LoadBalancer # 외부에서 브라우저로 접속할 수 있도록 AWS 로드밸런서를 생성.
  selector:
    app: smart-safety-frontend
  ports:
  - port: 80
    targetPort: 80